# Generated by Django 5.1.5 on 2025-02-05 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0015_tbl_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=30)),
                ('seller_email', models.CharField(max_length=30)),
                ('seller_contact', models.CharField(max_length=30)),
                ('seller_address', models.CharField(max_length=30)),
                ('seller_logo', models.FileField(upload_to='Assets/Seller/logo/')),
                ('seller_proof', models.FileField(upload_to='Assets/Seller/proof/')),
                ('seller_password', models.CharField(max_length=30)),
                ('seller_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
