# Generated by Django 5.1.5 on 2025-02-05 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_seller',
        ),
    ]
