# Generated by Django 5.1.5 on 2025-02-10 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0015_tbl_employee'),
        ('Guest', '0003_tbl_deliveryagent'),
        ('Seller', '0002_delete_tbl_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_photo', models.FileField(upload_to='Assets/Seller/product/')),
                ('product_description', models.CharField(max_length=30)),
                ('product_price', models.CharField(max_length=30)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_seller')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_subcategory')),
            ],
        ),
    ]
