# Generated by Django 5.1.5 on 2025-01-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_admin',
            new_name='tbl_adminreg',
        ),
    ]
