# Generated by Django 5.1.5 on 2025-01-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0010_tbl_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_subcategory',
        ),
    ]
