# Generated by Django 5.1.5 on 2025-02-05 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0015_tbl_employee'),
        ('Guest', '0002_tbl_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_deliveryagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryagent_name', models.CharField(max_length=30)),
                ('deliveryagent_email', models.CharField(max_length=30)),
                ('deliveryagent_contact', models.CharField(max_length=30)),
                ('deliveryagent_address', models.CharField(max_length=30)),
                ('deliveryagent_photo', models.FileField(upload_to='Assets/DeliveryAgent/photo/')),
                ('deliveryagent_proof', models.FileField(upload_to='Assets/DeliveryAgent/proof/')),
                ('deliveryagent_password', models.CharField(max_length=30)),
                ('deliveryagent_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
